# Generated by Django 5.1 on 2024-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_alter_manuals_files_alter_manuals_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuals',
            name='files',
            field=models.FileField(blank=True, default='default.jpg', upload_to='manuals/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='manuals',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='manuals/%Y/%m/%d/'),
        ),
    ]
