# Generated by Django 5.1 on 2024-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_alter_manuals_files_alter_manuals_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuals',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manuals',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
