# Generated by Django 5.1 on 2024-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userssite_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssite',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
